### PR TITLE
README instructions for running locally, update pip packages to resolve error

### PR DESCRIPTION
**Pull request by limsammy**
Add section and step-by-step instructions for running locally without docker

~~There is one step that can be removed (upgrading pip packages to latest to resolve pydantic/fastapi error when app loads `login_for_access_token`  route) once I add those updated requirement.txt's to the PR.~~

~~Since I will likely be removing that entire step (and the explanation I have added inline) I will put that here in the PR:~~

EDIT: that part has been removed and requirements updated to latest with `pip-compile`.

> _Explanation for this error:_ Without having done this I couldn't launch the uvicorn server without app.core.auth.login_for_access_token() raising an exception: RecursionError: maximum recursion depth exceeded django model inheritance. After some research I found an issue on the FastAPI repo in which the cause was found to be a mismatch in Pydantic and FastAPI versions. I decided to go ahead and update all of the pip packages and have the server running. I will add those updated requirements.txt files to this PR as well. Will likely remove this step once I have added those commits to the PR.

### CODE REVIEW

**Comment by limsammy** [comment]
Hm. Checking files changed only shows mypy was upgraded, so I'm not sure if that error will be resolved or not with a fresh project setup and running locally.

**Comment by limsammy** [comment]
For anyone wanting to run locally and _does_ run into that error, this fixed it for me:

```bash
pip install cffi click fastapi gunicorn h11 isort mypy packaging pathspec pip-tools pluggy pydantic PyJWT pytest python-dotenv regex setuptools six starlette typing-extensions uvicorn -U
    ```

**Comment by rednafi** [comment]
Thanks for the PR. I'll test it out on my local machine and add dependabot to the repo.

**Comment by rednafi** [comment]
I've updated all the dependencies to the latest version and added Dependabot to the repo for doing this automatically from now on. Also, I've added another section with the instructions to run this locally. Also, I didn't want to introduce another third party tool like `pyenv` in the instruction section. This can be marked as resolved. Thank you for the help.

**Pull request closed without merging**
